[tool.poetry]
name = "transimage"
version = "2.0.0"
description = "CLI tool for converting images between different formats and creating GIFs from image sequences, directories, or video files. Supports JPG, PNG, BMP, and WebP."
authors = ["Daethyra <109057945+Daethyra@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "transimage", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"
pillow = ">=11.0.0,<12.0.0"

[tool.poetry.group.dev.dependencies]
black = ">=24.10.0"
flake8 = ">=7.1.2"
pytest = ">=8.4.1"

[tool.poetry.extras]
opencv = ["opencv-python-headless"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
transimage = "transimage.__main__:main"